config/routes.rb
ProductPedia::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'high_voltage/pages#show', id: 'homepage'
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :delete] do
    member do
      post 	  'favorite'
      delete  'remove_favorite'
  	end
    collection do
      get :autocomplete
    end
  end
  resources :product_imports do
    collection do
      post 'import'
    end
  end
  resources :product_steps
  match 'ingredients',    to: 'ingredients#index',      via: :get
  match 'nutritions',     to: 'nutritions#index',       via: :get
  match 'distributers',   to: 'distributers#index',     via: :get
  match 'manufacturers',  to: 'manufacturers#index',    via: :get
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :users, :through => :favorites
  has_many :favorites
  has_many :bar_codes
  has_many :product_nuts
  has_many :nutritions, :through => :product_nuts
  has_many :product_ingredients
  has_many :ingredients, :through => :product_ingredients
  has_many :distributers
  has_many :distribution_companies, :through => :distributers, :source => :company
  has_many :new_infos
  has_many :manufacturers
  has_many :manufacture_companies, :through => :manufacturers, :source => :company
  belongs_to :category
  belongs_to :owner, class_name: "User"

  accepts_nested_attributes_for :bar_codes, :product_nuts

  attr_reader :ingredient_tokens
  attr_reader :nutrition_tokens
  attr_reader :distribution_company_tokens
  attr_reader :manufacture_company_tokens

  validates :name, :presence => true
  validates :description, :presence => true
  validates :category_id, :presence => true
  # validates :ingredient_tokens, :presence => true
  # validates :nutrition_tokens, :presence => true


  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:styles/PixarBall.jpg"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  searchkick text_start: [:name]

  # def self.search(search)
  # 	if search
  #     where("name LIKE ?", "%#{search}%")
  #     # find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  # 	else
  #   	all
  # 	end
  # end

  def self.favorite_list(user)
    favorite_product_ids = user.product_ids
    where("id in (?)", favorite_product_ids)
  end

  def ingredient_tokens=(ids)
    self.ingredient_ids = ids.split(",")
  end

  def nutrition_tokens=(ids)
    self.nutrition_ids = ids.split(",")
  end

  def distribution_company_tokens=(ids)
    self.distribution_company_ids = ids.split(",")
  end

  def manufacture_company_tokens=(ids)
    self.manufacture_company_ids = ids.split(",")
  end  
end

app/controllers/products_controller.rb
require 'will_paginate/array'

class ProductsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :autocomplete]

  def autocomplete
    # render json: [{"value" => "Product 1"}, {"value" => "Mercedes 1"}, {"value" => "Volvo 1" }]
    render json: Product.search(params[:search], fields: [{name: :text_start}], limit: 10).map { |p| { "value" => p.name } }
  end

  def favorite
  	@product = Product.find(params[:id])
  	@favorite = @product.favorites.build(user: current_user)
  	@favorite.save
  	redirect_to @product
  end

  def remove_favorite
    @product = Product.find(params[:id])
    @rm_favorite = Favorite.where(user_id: current_user.id, product_id: @product.id)
    if !@rm_favorite.empty?
      Favorite.delete(@rm_favorite.first.id)
    end
    redirect_to @product
  end

  def new
    @new_product = Product.new
    @product_import = ProductImport.new
    barcode = @new_product.bar_codes.build
    distributer = @new_product.distribution_companies
    manufacturer = @new_product.manufacture_companies
  end

  def create
    @new_product = Product.new(product_params)
    if @new_product.save
      session[:new_product] = @new_product.id
      redirect_to product_steps_path
      #redirect_to products_path(:p => @new_product.id)
    else
      @product_import = ProductImport.new
      render 'new'
    end
  end

  def index
    # @products = Product.search(params[:search])
    # @products = @products.page(params[:page]).per_page(10)
    if params[:search].present?
      @products = Product.search(params[:search], page: params[:page], per_page: 20)
    else
      @products = Product.all.page(params[:page]).per_page(20)
    end
  end

  def show
  	@product = Product.find(params[:id])
    @b_code = @product.bar_codes.first.barcode
    @ingredients = @product.ingredients
    @nutrition_facts = @product.nutritions
    @nutrit_amount = @product.product_nuts

    @dist = @product.distributers.first
    @distributer = Company.find(@dist.company_id)

    @manufact = @product.manufacturers.first
    @manufacturer = Company.find(@manufact.company_id)

    c = Category.all
    c.each do |category|
      @category = category if category.id == @product.category_id
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update_attributes(product_params)
  	  redirect_to product_path(@product)
    else
     render :edit
  	end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :picture, :warning, :ingredient_tokens, :nutrition_tokens, :distribution_company_tokens, :manufacture_company_tokens, :category_id, :bar_codes_attributes => [:barcode])
  end
end

app/views/products/_basic_product_info.html.erb
<div class="thumbnail">
  <%= image_tag @product.picture.url(:medium), size: '150x150' %></br>
  <div class="panel panel-default">
    <div class="panel-heading">Product name: <%= @product.name %></div>
      <div class="panel-body">
        <p> Found in: <%= @category.name %></p>
        <p class="distribution"> Distributer: <%= @distributer.name %></p>
        <p class="manufacture"> Manufacturer: <%= @manufacturer.name %></p>
        <p> Barcode: <%= @b_code %></p>
        <div>
          Product description:
          <%= text_field_tag :Description, @product.description%>
        </div>
      </div>  
  </div>    
</div>

app/views/products/_favorite_products.html.erb
<div class="panel panel-default">
	<div class="panel-heading">Favorites</div>
	<ul class="nav nav-pills">
	  <li>
	  	<%= link_to('Add',favorite_product_path(@product),method: :post )%>
	  </li>
	  <% if product_is_favorite(current_user, @product) %>
			<li class="addfav">
	    	<%= link_to('Remove ', remove_favorite_product_path(@product), method: :delete)%>
	    </li>
	    <li style = "font-size: 20px">
	    	<span class="glyphicon glyphicon-thumbs-up" style= "padding:10px "></span>
	    </li>
		<%end%>
    <% if  @product.owner_id == current_user.id %>
      <li>
        <%= link_to('Edit product', edit_product_path)%>
      </li>  
    <% end %>
	</ul>
	<ul class="list-group">
    <% current_user.favorite.each do |p| %>
      <li class="list-group-item">
        <%= p.name %>
      </li>
    <%end%>
  </ul>
</div>

app/views/products/_ingredients.html.erb
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">Ingredients(<%= @ingredients.count %>)</div>
		<div class="ingredientname">
			<% @ingredients.each do |ing| %>
				<%= ing.name %>,
			<%end%>
	  </div>
	</div>    
</div>

app/views/products/_moderator_products.html.erb
<div class="panel panel-default">
	<div class="panel-heading">Favorites</div>
	<ul class="nav nav-pills">
	  <li>
	  	<%= link_to('Submit',product_path(@product),method: :patch )%>
	  </li>
	</ul>
  <div style="text-align:center">
    <%= form_for @product do |f| %>
      <%= f.label :name %><br/>
      <%= f.text_field :name %><br/></br>
      <%= f.label :description %><br/>
      <%= f.text_field :description %><br/><br/>
      <%= f.label :picture %><br/>
      <%= f.file_field :picture %><br/>
      <%= f.submit "Submit change", method: :patch %>
    <% end %>

    <%= form_for @product_import do |p| %>
      <div class="field">
        <%= p.file_field :file %>
      </div>
      <div class="buttons">
        <%= p.submit "Import" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_nutrition_facts.html.erb
<div class="row">
	<div class="panel panel-default">
  	<div class="panel-heading">Nutrition facts</div>
		<table style="width:100%">
			<% @nutrition_facts.each do |nut| %>
				<% @nutrit_amount.each do |nut_amount| %>
					<tr>
						<% if nut.id == nut_amount.nutrition_id %>
							<td>
								<%= nut.name %>
							</td>
							<td class="nutritfield" style="text-align:right">
								<%= nut_amount.amount%>
							</td>
					  <%end%>
					</tr>
				<%end%>
		  <%end%>
		</table>
	</div>
</div>

app/views/products/_product_warning.html.erb
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">Warning</div>
    <% if @product.warning.blank? %>
      <p class="warning">No specific warnings are currently known for this product </p>
    <%else%>
      <p class="warning"><%= @product.warning %></p>
    <%end%>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container">
	<% if user_signed_in? && @product.owner_id == current_user.id %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">Edit basic product information</div>
          <div class="panel-body">
            <%= form_for @product do |f| %>
              <%= f.label :name %><br/>
              <%= f.text_field :name , class: "form-control" %><br/>
              <%= f.label :description %><br/>
              <%= f.text_area :description, rows: "3", cols: "35", class: "form-control" %></br>
              <%= f.label :category_id, "Category" %></br>
              <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Select a category"}, class: "form-control") %></br>
              <%= f.label :distribution_company_tokens, "Distributer" %>        
              <%= f.text_field :distribution_company_tokens , class: "form-control"%></br>
              <%= f.label :manufacture_company_tokens, "Manufacturer" %>        
              <%= f.text_field :manufacture_company_tokens, class: "form-control" %></br>
              <%= f.label :ingredient_tokens, "Ingredients" %>        
              <%= f.text_field :ingredient_tokens, class: "form-control" %></br>
              <%= f.label :nutrition_tokens, "Nutritions" %>        
              <%= f.text_field :nutrition_tokens, class: "form-control" %></br>
              <%= f.label :warning %><br/>
              <%= f.text_field :warning , class: "form-control"%><br/>
              <%= f.label :picture %><br/>
              <%= f.file_field :picture %><br/>
              <%= f.submit "Submit change", method: :patch , class: "btn btn-primary"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
	<% else %>
		<%= render :text => "U don't have rights for this page", :status => 500 %>
	<%end%>
</div>

app/views/products/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="center">
    <%= form_tag products_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search],class: "form-control",id: "product_search"%>
      </p>
      <p>
        <%= submit_tag "Search", :name => nil , class: "btn btn-default" %>
      </p>
    <% end %>
  </div>
  <h1>Products</h1>
  <div class="jumbotron">
    <div style="text-align:left">
      <%= button_to "New Product", new_product_path , method: :get, class: "btn btn-default"%>
    </div>
    <div class="list-group" style="margin: 0px auto;">
      <% @products.each do |product| %>
        <%= link_to product_path(product.id), class: "list-group-item" do %>
          <%= product.name %>
        <%end%>
      <%end%>
    </div>
    <%= will_paginate @products %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
	<% if user_signed_in? %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">Product data</div>
            <div class="panel-body">
              <p>Click below if u want to create products importing data from a file (Excel, ...)</p>
              <a href="#" id="show_id" onclick="document.getElementById('spoiler_id').style.display=''; document.getElementById('show_id').style.display='none';" class="link">[Open]</a>
              <span id="spoiler_id" style="display: none">
                <a onclick="document.getElementById('spoiler_id').style.display='none'; document.getElementById('show_id').style.display='';" class="link">[Close]</a>
                <%= form_for @product_import do |p| %>
                  </br>
                  <div class="field">
                    <%= p.file_field :file, id: "file"%>
                  </div></br>
                  <div class="buttons">
                    <%= p.submit "Import" ,class: "btn btn-primary"%>
                  </div>
                <% end %>
              </span>

            </br></br>
              <%= form_for @new_product do |f| %>
                <%= f.label :name, "Product name" %></br>
                <%= f.text_field :name , placeholder: "Product name", class: "form-control" %></br>
                <%= f.label :description, "Description" %></br>
                <%= f.text_area :description , placeholder: "Some Description" , rows: "3", cols: "35", class: "form-control" %></br>
                <%= f.fields_for :bar_codes do |builder|%>
                  <%= builder.label :barcode, "Bar code" %></br>
                  <%= builder.text_field :barcode , maxlength: "13", class: "form-control"%>
                <% end %></br>
                <%= f.label :category_id, "Category" %></br>
                <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Select a category"}, class: "form-control") %></br>
                <%= f.label :picture, "Picture" %></br>
                <%= f.file_field :picture , class: "btn btn-default"%></br>
                <%= f.submit "Next", method: :post , class: "btn btn-primary"%>
              <%end%>
            </div>  
          </div>
      </div>
    </div>
  <%end%>
</div>

app/views/products/show.html.erb
<div class="container">
	<% if user_signed_in? %>
    <div class="row">
      <div class="col-md-4">
        <%= render "basic_product_info" %>
      </div>
      <div class="col-md-4">
        <%= render "ingredients" %>
        <%= render "product_warning"%>
        <%= render "nutrition_facts"%>
      </div>
      <div class="col-md-4">
        <%= render "favorite_products" %>
      </div>
    </div>
  <% else %>
  	<div class="row">
  	  <div class="col-md-5">
  	 		<%= render "basic_product_info" %>
  		</div>
  		<div class="col-md-5">
  			<%= render "ingredients" %>
  			<%= render "product_warning"%>
  	 		<%= render "nutrition_facts"%>
  		</div>
  	</div>
  <% end %>
</div>